

# https://github.com/DoTheEvo/Traefik-v2-examples
version: "3.3"
services:
  picasa_dev:
    build:
      context: .
      dockerfile: Dockerfile_picasa
      args:
        buildno: 1
    image:
      picasa_img
    container_name: picasa_api_dev
    command:
      bash /startup.sh
    # env_file:
    #   - .env_develop
    environment:
      # Add the following line to your /etc/profile:
      # HOST_IP=`ip route | grep default | awk '{print $9}'`
      - ADMIN_PW=L0TRswhp
      - ADMIN_USERNAME=benjamin
      - ADMIN_EMAIL=benjamin.lewis.1000@gmail.com
      - CLIENT_FACE_PORT=44444
      - DB_FILES_LOCATION=/mnt/data/appdata/django_picasa/dev/database
      - DB_NAME=picasa
      - DB_PWD=UUDKrIXzGlz1Uneqnm7l3JZ0E
      - DB_USER=benjamin
      - DJANGO_SECRET_KEY=1>3{xdA|UhPca+pH@lWQ=be\-Dm4qR%Hn0]9[jw*SFv#"j.dX(
      - DOMAINNAME=exploretheworld.tech
      - MEDIA_DOMAIN=picasamedia_dev.exploretheworld.tech
      - MEDIA_FILES_LOCATION=/mnt/data/appdata/django_picasa/dev/media_files
      - PHOTO_ROOT=/mnt/data/samba_share/Photos/tmp_pic
      - WEBAPP_DOMAIN=picasa_dev.exploretheworld.tech
      - DJANGO_FILES_ROOT=/home/benjamin/git_repos/django_picasa
      - IN_DOCKER=True
      - TEST_PHOTOS_FILEPOPULATE=/mnt/data/appdata/django_picasa/test_files/test_imgs_filepopulate
      - LOG_LOCATION=/mnt/data/appdata/django_picasa/dev/logs
      - PRODUCTION=False
      - APACHE_USER=picasa_data
      - APACHE_PWD=Z8su8qxzw3SCupVujEFSVXt6G
      - STATIC_LOCATION=/home/benjamin/git_repos/django_picasa/picasa/static
    ports:
      - "${CLIENT_FACE_PORT}:${CLIENT_FACE_PORT}/udp"
      #- "5001:5001/udp"
     # - 5000:5000
     # - 5001:5001
     # - 44444:44444
    volumes:
      - ${DJANGO_FILES_ROOT}:/code
      - ${PHOTO_ROOT}:/photos:ro
      - ${TEST_PHOTOS_FILEPOPULATE}:/test_imgs_filepopulate
      - ${MEDIA_FILES_LOCATION}:/media
      - ${LOG_LOCATION}:/var/log/picasa
    depends_on:
      - db_django_dev
    networks:
      - traefik_proxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.picasa.rule=Host(`${WEBAPP_DOMAIN}`)"
      - "traefik.http.routers.picasa.tls.certresolver=leresolver"
      - "traefik.http.routers.picasa.entrypoints=websecure"
      - "traefik.http.services.picasa.loadbalancer.server.port=8000"
      - "traefik.http.services.picasa.loadbalancer.healthcheck.hostname=${WEBAPP_DOMAIN}"
      - "traefik.http.middlewares.picasa.redirectscheme.scheme=https"
      - "traefik.http.middlewares.picasa.redirectscheme.permanent=true"


  db_django_dev:
#    build:
#      context: .
#      dockerfile: Dockerfile_postgres
#    image: postgres_init
#FROM postgres:12.1-alpine
# WORKDIR /docker-entrypoint-initdb.d
# ADD psql_init.sh .

    image: postgres:12.1-alpine
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      - DB_FILES_LOCATION=/mnt/data/appdata/django_picasa/dev/database
      - DB_NAME=picasa
      - DB_PWD=UUDKrIXzGlz1Uneqnm7l3JZ0E
      - DB_USER=benjamin
#      PGDATA: /database
    volumes:
      - ${DB_FILES_LOCATION}:/var/lib/postgresql/data
      - ${DJANGO_FILES_ROOT}/dockerize/psql_init_dev.sh:/docker-entrypoint-initdb.d/psql_init.sh
      # Initialization script - see Postgres Docker documentation.

    labels:
      - "user=postgres"
    container_name: db_picasa_dev
    networks:
      - traefik_proxy

  task_redis_dev:
    image: redis:5.0-alpine
    # env_file:
    #   - .env_picasa
    restart: always
    env_file:
      - .env
    networks:
      - traefik_proxy
    container_name: redis_picasa_dev

  apache_fileserve_dev:
    # image: httpd:2.4-alpine
    build:
      context: . 
      dockerfile: Dockerfile_apache
      args:
        buildno: 1
    image:
      httpd_image
    container_name: picasa_media_apache_dev
  
    environment:
      # Add the following line to your /etc/profile:
      # HOST_IP=`ip route | grep default | awk '{print $9}'`
      - ADMIN_PW=L0TRswhp
      - ADMIN_USERNAME=benjamin
      - ADMIN_EMAIL=benjamin.lewis.1000@gmail.com
      - CLIENT_FACE_PORT=44444
      - DB_FILES_LOCATION=/mnt/data/appdata/django_picasa/dev/database
      - DB_NAME=picasa
      - DB_PWD=UUDKrIXzGlz1Uneqnm7l3JZ0E
      - DB_USER=benjamin
      - DJANGO_SECRET_KEY=1>3{xdA|UhPca+pH@lWQ=be\-Dm4qR%Hn0]9[jw*SFv#"j.dX(
      - DOMAINNAME=exploretheworld.tech
      - MEDIA_DOMAIN=picasamedia_dev.exploretheworld.tech
      - MEDIA_FILES_LOCATION=/mnt/data/appdata/django_picasa/dev/media_files
      - PHOTO_ROOT=/mnt/data/samba_share/Photos/tmp_pic
      - WEBAPP_DOMAIN=picasa_dev.exploretheworld.tech
      - DJANGO_FILES_ROOT=/home/benjamin/git_repos/django_picasa
      - IN_DOCKER=True
      - TEST_PHOTOS_FILEPOPULATE=/mnt/data/appdata/django_picasa/test_files/test_imgs_filepopulate
      - LOG_LOCATION=/mnt/data/appdata/django_picasa/dev/logs
      - PRODUCTION=False
      - APACHE_USER=picasa_data
      - APACHE_PWD=Z8su8qxzw3SCupVujEFSVXt6G
      - STATIC_LOCATION=/home/benjamin/git_repos/django_picasa/picasa/static
#    expose:
#      - '80'
    # environment:
    #   - MEDIA_FILES_LOCATION=${MEDIA_FILES_LOCATION}
    restart: always
    volumes:
      # - ${MEDIA_FILES_LOCATION}:/usr/local/apache2/htdocs/
      - ${MEDIA_FILES_LOCATION}:/var/www/media:ro
      - ${STATIC_LOCATION}:/var/www/static:ro
      - ${PHOTO_ROOT}:/var/www/full_res:ro
      - ${DJANGO_FILES_ROOT}/dockerize/apache_config_dev/000-default.config:/etc/apache2/sites-enabled/000-default.conf
      - ${DJANGO_FILES_ROOT}/dockerize/apache_config_dev/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ${DJANGO_FILES_ROOT}/dockerize/apache_config_dev/apache_pwd.pwd:/usr/local/apache2/.htpasswd 
    networks:
      - traefik_proxy
    labels:
#      - "traefik.backend=picasa_media"
#      - "traefik.frontend.rule=Host:${MEDIA_DOMAIN}"
      - "traefik.enable=true"
#      - "traefik.port=80"
#      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.apache_fileserve.rule=Host(`${MEDIA_DOMAIN}`)"
      - "traefik.http.routers.apache_fileserve.tls.certresolver=leresolver"
      - "traefik.http.routers.apache_fileserve.entrypoints=websecure"
      #- "traefik.http.routers.traefik.middlewares=authtraefik"
      #- "traefik.http.middlewares.authtraefik.basicauth.users=admin:$apr1$ly25xhfg$d2eLiOIOnM.IbsZ6Cfb760" # admin/movie based one


networks:
  default: 
    driver: bridge
  traefik_proxy:
    external: true
  #traefik_default:
  #  external: true
#       name: traefik_default
