# FROM debian:buster
FROM ubuntu:22.04
WORKDIR /code

RUN apt update

RUN apt install cmake -y
RUN apt install python3-pip -y
RUN apt install -y wget 
RUN apt install exiv2 -y
RUN apt install -y gir1.2-gexiv2-0.10
# RUN apt install python3.11-venv -y

# RUN python3 -m venv /code/venv

# Add our requirements.txt
RUN pip3 install opencv-python-headless>=4.4.0.44 
RUN pip3 install face_recognition 
RUN pip3 install face-recognition-models==0.3.0
RUN pip3 install facenet-pytorch==2.5.0   

RUN apt install libgirepository-1.0-1
ADD requirements.txt /code/requirements.txt
RUN apt install libffi-dev
RUN pip3 install -r /code/requirements.txt 

RUN apt install exempi -y

RUN apt remove cmake -y

RUN cp /usr/bin/python3 /usr/bin/python

# RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN apt install -y python3-gi 
# RUN apt install -y gir1.2-gtk-3.0
# RUN apt install -y python3-gi-cairo 

# RUN pip3 install PyJWT==1.7.1

RUN DEBIAN_FRONTEND=noninteractive apt install -y postgresql # postgresql-contrib
RUN rm -r /var/lib/apt/lists

ADD startup.sh /startup.sh

RUN groupadd --gid 1001 usergrp && useradd --uid 1001 --gid usergrp -m user 

WORKDIR /code
