
version: "3.3"
services:
  picasa:
    build:
      context: .
      dockerfile: Dockerfile_picasa
      args:
        buildno: 1
    image:
      picasa_img
    command:
      bash /startup.sh
    env_file:
      - .env
#    ports:
#      - "8000:8000"
    volumes:
      - ${DJANGO_FILES_ROOT}:/code
      - ${PHOTO_ROOT}:/photos:ro
      - ${TEST_PHOTOS_FILEPOPULATE}:/test_imgs_filepopulate
      - ${MEDIA_FILES_LOCATION}:/media
      - ${LOG_LOCATION}:/var/log/picasa
    depends_on:
      - db_django
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=picasa"
      - "traefik.enable=true"
#      - "traefik.webapp.enable=true"
      - "traefik.webapp.frontend.rule=Host:${WEBAPP_DOMAIN}"
      - "traefik.webapp.port=8000"
#      - "traefik.flower.enable=true"
      - "traefik.flower.frontend.rule=Host:flower.${DOMAINNAME}"
      - "traefik.flower.port=5555"
      - "traefik.docker.network=traefik_proxy"

      # Need to start postgresql service

  db_django:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    image: postgres_init
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      PGDATA: /database
    volumes:
      - ${DB_FILES_LOCATION}:/var/lib/postgresql/data
      # Initialization script - see Postgres Docker documentation.

    labels:
      - "user=postgres"
    container_name: db_picasa  
    networks:
      - traefik_proxy

  task_redis:
    image: redis:5.0-alpine
    # env_file:
    #   - .env_picasa
    restart: always
    env_file:
      - .env
    networks:
      - traefik_proxy

  apache_fileserve:
    # image: httpd:2.4-alpine
    build:
      context: . 
      dockerfile: Dockerfile_apache
      args:
        buildno: 1
    image:
      httpd_image
    env_file:
      - .env
#    expose:
#      - '80'
    # environment:
    #   - MEDIA_FILES_LOCATION=${MEDIA_FILES_LOCATION}
    restart: always
    volumes:
      # - ${MEDIA_FILES_LOCATION}:/usr/local/apache2/htdocs/
      - ${MEDIA_FILES_LOCATION}:/var/www/media
      - ${STATIC_LOCATION}:/var/www/static
      - ${DJANGO_FILES_ROOT}/dockerize/apache_config/000-default.config:/etc/apache2/sites-enabled/000-default.conf
      - ${DJANGO_FILES_ROOT}/dockerize/apache_config/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ${DJANGO_FILES_ROOT}/dockerize/apache_config/apache_pwd.pwd:/usr/local/apache2/.htpasswd 
    networks:
      - traefik_proxy
    labels:
      - "traefik.backend=picasa_media"
      - "traefik.frontend.rule=Host:${MEDIA_DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"

networks:
  default: 
    driver: bridge
  traefik_proxy:
    external: true
  #traefik_default:
  #  external: true
#       name: traefik_default
