# Generated by Django 2.2.4 on 2019-10-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_img', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(editable=False, upload_to='thumbs_uploadimg')),
            ],
        ),
    ]
