# Generated by Django 6.0.8 on 2026-09-11 03:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=1024)),
                ('total_size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('chunk_size', models.BigIntegerField()),
                ('total_chunks', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('size', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.uploadsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'chunk_index'), name='unique_session_chunk_index')],
            },
        ),
    ]
