# Generated by Django 6.0.8 on 2026-09-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePhotosWatchedAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GooglePhotosSyncedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_media_item_id', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=1024)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('watched_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_items', to='api.googlephotoswatchedalbum')),
            ],
        ),
    ]
