# Generated by Django 6.0.8 on 2026-09-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_googlephotoswatchedalbum_googlephotossynceditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePhotosCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('refresh_token', models.CharField(blank=True, default='', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
