# Generated by Django 2.2.4 on 2019-09-17 11:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('filename', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Filename must be a JPG', regex='\\.[j|J][p|P][e|E]?[g|G]$')])),
                ('pixel_hash', models.CharField(default=-1, max_length=64)),
                ('file_hash', models.CharField(default=-1, max_length=64)),
                ('id', models.AutoField(default=-1, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dateTaken', models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0))),
                ('dateTakenValid', models.BooleanField(default=False)),
                ('isProcessed', models.BooleanField(default=False)),
                ('orientation', models.IntegerField(default=-8008)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filepopulator.Directory')),
            ],
        ),
    ]
