# Generated by Django 5.2.6 on 2025-09-19 02:06

import datetime
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import filepopulator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_path', models.CharField(max_length=512, unique=True)),
                ('mean_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('mean_datesec', models.FloatField(default=-1)),
                ('first_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_datesec', models.FloatField(default=-1)),
                ('num_images', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DuplicateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=1024, validators=[django.core.validators.RegexValidator(message='Filename must be a JPG', regex='\\.[j|J][p|P][e|E]?[g|G]$')])),
                ('pixel_hash', models.CharField(default=-1, max_length=64)),
                ('file_hash', models.CharField(default=-1, max_length=64)),
                ('full_res_path', models.CharField(default=None, max_length=1024, null=True)),
                ('thumbnail_big', models.ImageField(default=None, editable=False, upload_to=filepopulator.models.thumbnail_big_path)),
                ('thumbnail_medium', models.ImageField(default=None, editable=False, upload_to=filepopulator.models.thumbnail_med_path)),
                ('thumbnail_small', models.ImageField(default=None, editable=False, upload_to=filepopulator.models.thumbnail_small_path)),
                ('camera_make', models.CharField(blank=True, max_length=64, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=64, null=True)),
                ('flash_info', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('exposure_num', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('exposure_denom', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('focal_num', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('focal_denom', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('fnumber_num', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('fnumber_denom', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('iso_value', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('light_source', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)])),
                ('gps_lat_decimal', models.FloatField(default=-999, validators=[filepopulator.models.validate_lat])),
                ('gps_lon_decimal', models.FloatField(default=-999, validators=[filepopulator.models.validate_lon])),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dateTaken', models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0))),
                ('dateTakenUTC', models.FloatField(default=0)),
                ('dateTakenValid', models.BooleanField(default=False)),
                ('isProcessed', models.BooleanField(default=False)),
                ('orientation', models.IntegerField(default=-8008)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), blank=True, null=True, size=None)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_set', to='filepopulator.directory')),
            ],
        ),
    ]
