# Generated by Django 6.0.8 on 2026-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='image_load_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='image_load_failed',
            field=models.BooleanField(default=False),
        ),
    ]
