# Generated by Django 2.2.4 on 2019-09-18 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0002_auto_20190917_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='camera_make',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='camera_model',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='exposure_denom',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='exposure_num',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='flash_info',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='fnumber_denom',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='fnumber_num',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='focal_denom',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='focal_num',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='iso_value',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='light_source',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
