# Generated by Django 6.0.8 on 2026-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0002_imagefile_image_load_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024, unique=True)),
                ('error_message', models.TextField()),
                ('file_mod_time', models.FloatField()),
                ('first_failed_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
