# Generated by Django 2.2.4 on 2019-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0003_auto_20190918_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='gps_lat_decimal',
            field=models.FloatField(default=-999),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='gps_lon_decimal',
            field=models.FloatField(default=-999),
        ),
    ]
