# Generated by Django 6.0.8 on 2026-08-26 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0003_failedimagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='gps_source',
            field=models.CharField(blank=True, default='exif', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='filename',
            field=models.CharField(db_index=True, max_length=1024, validators=[django.core.validators.RegexValidator(message='Filename must be a JPG, JPEG, HEIC, or HEIF', regex='\\.(?:[jJ][pP][eE]?[gG]|[hH][eE][iI][cC]|[hH][eE][iI][fF])$')]),
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('locality', models.CharField(blank=True, max_length=256, null=True)),
                ('county', models.CharField(blank=True, max_length=256, null=True)),
                ('state', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('display_name', models.CharField(blank=True, max_length=512, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('lookup_failed', models.BooleanField(default=False)),
                ('lookup_error', models.TextField(blank=True, null=True)),
                ('nearest_metro_name', models.CharField(blank=True, max_length=256, null=True)),
                ('nearest_metro_distance_km', models.FloatField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lat', 'lon'), name='unique_geocode_cache_coordinate')],
            },
        ),
        migrations.AddField(
            model_name='imagefile',
            name='geocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='filepopulator.geocodecache'),
        ),
    ]
