# Generated by Django 6.0.8 on 2026-08-27 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0004_imagefile_gps_source_alter_imagefile_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='phash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='similarity_checked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='SimilarImagePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamming_distance', models.PositiveSmallIntegerField()),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_higher_id', to='filepopulator.imagefile')),
                ('image_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_lower_id', to='filepopulator.imagefile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('image_a', 'image_b'), name='unique_similar_image_pair')],
            },
        ),
    ]
