# Generated by Django 6.0.8 on 2026-09-04 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0005_imagefile_phash_imagefile_similarity_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatefile',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='filepopulator.imagefile'),
        ),
    ]
