# Generated by Django 6.0.8 on 2026-09-07 18:24

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import filepopulator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0006_duplicatefile_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedVideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024, unique=True)),
                ('error_message', models.TextField()),
                ('file_mod_time', models.FloatField()),
                ('first_failed_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=1024, validators=[django.core.validators.RegexValidator(message='Filename must be a supported video format', regex='\\.(?:[mM][pP]4|[mM][oO][vV]|[mM][pP][gG]|[aA][vV][iI]|[mM]2[tT][sS]|[mM][tT][sS]|[wW][mM][vV]|3[gG][pP][pP]?|[mM]4[vV]|[mM][kK][vV])$')])),
                ('file_hash', models.CharField(default=-1, max_length=64)),
                ('thumbnail_big', models.ImageField(default=None, editable=False, upload_to=filepopulator.models.thumbnail_big_path)),
                ('thumbnail_medium', models.ImageField(default=None, editable=False, upload_to=filepopulator.models.thumbnail_med_path)),
                ('thumbnail_small', models.ImageField(default=None, editable=False, upload_to=filepopulator.models.thumbnail_small_path)),
                ('duration_seconds', models.FloatField(default=0)),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('codec', models.CharField(blank=True, max_length=32, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=64, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=64, null=True)),
                ('rotation', models.IntegerField(default=0)),
                ('gps_lat_decimal', models.FloatField(default=-999, validators=[filepopulator.models.validate_lat])),
                ('gps_lon_decimal', models.FloatField(default=-999, validators=[filepopulator.models.validate_lon])),
                ('gps_source', models.CharField(blank=True, default='exif', max_length=64, null=True)),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateTaken', models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0))),
                ('dateTakenUTC', models.FloatField(default=0)),
                ('dateTakenValid', models.BooleanField(default=False)),
                ('isProcessed', models.BooleanField(default=False)),
                ('video_load_failed', models.BooleanField(default=False)),
                ('video_load_error', models.TextField(blank=True, null=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_set', to='filepopulator.directory')),
                ('geocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='filepopulator.geocodecache')),
            ],
        ),
    ]
