# Generated by Django 6.0.8 on 2026-09-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0007_failedvideofile_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
