# Generated by Django 6.0.8 on 2026-09-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0008_videofile_file_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='field_order',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
