# Generated by Django 6.0.8 on 2026-09-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0009_videofile_field_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodecache',
            name='metro_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geocodecache',
            name='metro_validated',
            field=models.BooleanField(default=False),
        ),
    ]
