# Generated by Django 6.0.8 on 2026-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0010_geocodecache_metro_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodecache',
            name='locality_is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
