# Generated by Django 6.0.8 on 2026-09-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0011_geocodecache_locality_is_approximate'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='face_extraction_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='face_extraction_failed',
            field=models.BooleanField(default=False),
        ),
    ]
