# Generated by Django 6.0.8 on 2026-09-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0012_videofile_face_extraction_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='face_extraction_timeout_count',
            field=models.IntegerField(default=0),
        ),
    ]
