# Generated by Django 6.0.8 on 2026-09-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0013_videofile_face_extraction_timeout_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='face_extraction_timeout_count',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
