# Generated by Django 6.0.8 on 2026-09-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0014_alter_videofile_face_extraction_timeout_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='DuplicateVideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='filepopulator.videofile')),
            ],
        ),
    ]
