# Generated by Django 6.0.8 on 2026-09-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0015_videofile_content_hash_duplicatevideofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='color_transfer',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
