# Generated by Django 6.0.8 on 2026-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0016_videofile_color_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='sar_scale_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
