# Generated by Django 6.0.8 on 2026-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepopulator', '0017_videofile_sar_scale_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
