"""
Django settings for picasa project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from celery.schedules import crontab
from datetime import timedelta, datetime
import logging
import os
import random
import re
import string
# from .custom_cors import LocalNetworkCorsMiddleware

today = datetime.today()
random_seed = today.year * 10000 + today.month * 100 + today.day
random.seed(random_seed)

# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THIS_DIR = os.path.dirname(os.path.abspath(__file__))

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/2.2/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if 'IN_DOCKER' in os.environ.keys():
    in_docker = True
else:
    in_docker = False

production = False
if 'PRODUCTION' in os.environ.keys():
    if os.environ['PRODUCTION'] == 'True':
        production = True

if in_docker:
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
    DB_NAME = os.environ['DB_NAME']
    DB_USER = os.environ['DB_USER']
    DB_PASS = os.environ['DB_PWD']
    DEV = os.environ['DEV'] == 'True'
    MEDIA_ROOT = '/media' # os.environ['MEDIA_FILES_LOCATION']
    if DEV:
        REDIS_HOST = 'task_redis_dev'
        DB_HOST = 'db_picasa_dev'
    else:
        REDIS_HOST = 'task_redis'
        DB_HOST = 'db_picasa'
        
    PHOTO_ROOT = '/photos'
    PHOTO_ROOT_RW = '/photos_rw'
    TEST_IMG_DIR_FILEPOPULATE = '/test_imgs_filepopulate'
    ALLOWED_HOSTS = ['localhost',
        '127.0.0.1', 
        os.environ['DOMAINNAME'], 
        os.environ['API_DOMAIN'], 
        'flower.' + os.environ['DOMAINNAME'],
        os.environ['TAILSCALE_HOST_IP'],
        os.environ['DOCKER_HOST_IP'],
    ]
#    STATIC_URL = 'http://localhost/static/'
#    MEDIA_URL  = 'http://localhost:8080/'
    STATIC_URL = 'https://' + os.environ['MEDIA_DOMAIN'] + '/static/'
    MEDIA_URL = 'https://' + os.environ['MEDIA_DOMAIN'] + '/media/'
    LOG_DIR = '/var/log/picasa'
    STATIC_ROOT = os.environ['PICASA_STATIC_LOCATION']
    MEDIA_URL_USER = os.environ['APACHE_USER']
    MEDIA_URL_PW = os.environ['APACHE_PWD']
    HOST_DOMAIN = 'https://' + os.environ['API_DOMAIN']
else:
    DB_NAME = 'picasa'
    DB_USER = 'benjamin'
    DB_PASS = 'lewis'
    DB_HOST = 'localhost'
    REDIS_HOST = 'localhost'
    MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    PHOTO_ROOT = '/home/benjamin/git_repos/picasa_files/actual_imgs'
    TEST_IMG_DIR_FILEPOPULATE = '/home/benjamin/git_repos/picasa_files/test_imgs'

    STATIC_URL = 'http://localhost/static/'
    MEDIA_URL  = 'http://localhost/media/'
    STATIC_SERVER = '/var/www/html/static'
    LOG_DIR = '/home/benjamin/git_repos/picasa_files/logs'
    HOST_DOMAIN = 'http://localhost'

RANDOM_ACCESS_KEY = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(32)])
# print(MEDIA_URL)

# Set up logging
formatter = logging.Formatter('%(levelname)s | %(asctime)s - %(message)s')
LOGGER = logging.getLogger("__main__")
LOGGER.setLevel(logging.DEBUG)
LOGGER.propagate = False

fh_low = logging.FileHandler(os.path.join(LOG_DIR, 'picasa_debug.log'), 'a')
fh_low.setLevel(logging.DEBUG)
fh_low.setFormatter(formatter)
LOGGER.addHandler(fh_low)

fh_high = logging.FileHandler(os.path.join(LOG_DIR, 'picasa_important.log'), 'a')
fh_high.setLevel(logging.WARNING)
fh_high.setFormatter(formatter)
LOGGER.addHandler(fh_high)

fh_mid = logging.FileHandler(os.path.join(LOG_DIR, 'picasa_lite_debug.log'), 'a')
fh_mid.setLevel(logging.INFO)
fh_mid.setFormatter(formatter)
LOGGER.addHandler(fh_mid)

ch = logging.StreamHandler()
ch.setLevel(logging.ERROR)
ch.setFormatter(formatter)
LOGGER.addHandler(ch)

if in_docker:
    LOGGER.warning("Allowed hosts is wrong in docker")

LOGGER.debug(f"Are we in production? {production}")

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

LOCKFILE = '/locks/adding.lock' # path.join(PROJECT_ROOT, 'adding.lock')
FACE_LOCKFILE = '/locks/face_add.lock'
CLASSIFY_LOCKFILE = '/locks/classify.lock'
DUPLICATES_FILE = '/code/duplicates.csv'

# Nominatim's usage policy requires a real, identifying user agent -- it
# rejects/blocks requests using geopy's generic default.
NOMINATIM_USER_AGENT = 'django_picasa (self-hosted photo library, contact: ' + os.environ.get('NOMINATIM_CONTACT_EMAIL', 'unset@example.com') + ')'

# Max phash Hamming distance (out of 64 bits) for two images to be
# considered near-duplicates. Chosen from real production photos: exact
# recompressed duplicates and true repeat-shots scored 0-6, genuinely
# different (even time-adjacent) photos scored 20+ -- see
# filepopulator/similarity.py.
PHASH_SIMILARITY_THRESHOLD = 10
# if os.path.isfile(LOCKFILE):
#     os.remove(LOCKFILE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # True # not production # False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    # 'periodic.apps.PeriodicConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'filepopulator',
    'common', 
    'train_classify',
    'face_manager',
    'api',
    'filters',
    # 'webpack_loader',
    # 'upload_img',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect', # <-- The OIDC bridge
]

# You also must specify a SITE_ID if using django.contrib.sites
SITE_ID = 1
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'picasa.custom_cors.LocalNetworkCorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]


# To get the Authelia secret:
# 1) Generate the client secret plaintext, put it in your .env file
# 2) Generate the hash for this in Authelia, with
# docker exec -it authelia authelia crypto hash generate pbkdf2 --variant sha512 --password "your_chosen_cleartext_secret"
# 3) Add the client to Authelia's configuration.yaml file:
'''
identity_providers:

  ##
  ## OpenID Connect (Identity Provider)
  ##
  ## It's recommended you read the documentation before configuration of this section.
  ## See: https://www.authelia.com/c/oidc/provider
  oidc:
    clients:
      - client_id: 'django_picasa'            # <-- This is your client_id
        client_name: 'Django Face Tagging'
        client_secret: 'HASHED_SECRET' # <-- The HASHED secret from Step 2
        public: false
        authorization_policy: 'one_factor'       # or 'two_factor' depending on your preference
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        redirect_uris:
        # Whatever your URL is
          - 'https://facewire.exploretheworld.tech/accounts/oidc/authelia/login/callback/'
'''
# 4) Match it over to the below block.
SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "authelia",
                "name": "Authelia SSO",
                "client_id": "django_picasa",
                "secret": os.environ['AUTHELIA_SECRET'],
                "settings": {
                    "server_url": "https://auth.exploretheworld.tech/.well-known/openid-configuration"
                }
            }
        ]
    }
}

####################
# AUTHELIA
####################

# Trust the email from Authelia and log into the matching local account
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True

# Automatically link the Authelia social profile to the local account
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# Bypass the "You are about to sign in" intermediate warning page
SOCIALACCOUNT_LOGIN_ON_GET = True

# --- PhotoVerify mobile app: direct OIDC bearer-token auth ---------------
# The mobile app runs its own Authorization Code + PKCE flow against
# Authelia (public client) and sends the ID token as a Bearer token.
# api/authentication.py:AutheliaOIDCAuthentication validates it.
# Non-secret values, so plain defaults keep local dev working without new
# required env vars (see CLAUDE.md note on both-branch settings).
AUTHELIA_ISSUER = os.environ.get(
    'AUTHELIA_ISSUER', 'https://auth.exploretheworld.tech'
)
AUTHELIA_JWKS_URL = os.environ.get(
    'AUTHELIA_JWKS_URL', f'{AUTHELIA_ISSUER}/jwks.json'
)
AUTHELIA_MOBILE_CLIENT_ID = os.environ.get(
    'AUTHELIA_MOBILE_CLIENT_ID', 'photoverify_mobile'
)
# Authelia signing keys rotate very rarely (only on an explicit config
# change), so cache them for a day. A shorter lifespan just means more
# refetches -> more chances for a transient fetch failure to reject a
# valid token. api/authentication.py also retries the fetch and falls
# back to the last-known-good key, so key rotation is still picked up.
AUTHELIA_JWKS_CACHE_SECONDS = int(
    os.environ.get('AUTHELIA_JWKS_CACHE_SECONDS', '86400')
)

# Where to send users after a successful login
LOGIN_REDIRECT_URL = f"https://{os.environ['API_DOMAIN']}/"

# Where to send users if they log out

# Force Django's login shortcuts to point directly to your Authelia flow
LOGIN_URL = '/accounts/oidc/authelia/login/'

# Bouncing a Django logout request straight out to Authelia's logout portal
LOGOUT_REDIRECT_URL = 'https://auth.exploretheworld.tech/logout'
# Force Django to destroy its session cookie when the browser tab closes
SESSION_COOKIE_AGE = 1800  # Expires after 30 minutes of inactivity
# The comment above was aspirational, not actual: Django only resends a
# fresh Set-Cookie (renewing SESSION_COOKIE_AGE from "now") when the
# session is written to on a given request. Without this, the cookie's
# expiry is fixed at login time + 30 minutes, active or not - a user
# working continuously for 30+ minutes gets logged out anyway, and it
# happens silently (the frontend has no periodic re-check - see
# dev_facewire's isLoggedIn.jsx, only called once at mount). This makes
# every authenticated request re-save the session, turning the 30-minute
# window into a real sliding inactivity timeout as originally intended.
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_DOMAIN = '.exploretheworld.tech'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
        },
    },
}

# Get the Django Rest Framework to use https in pagination links
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_ALL_ORIGINS=False
# Crucial: This tells Django to accept incoming cookies from cross-origin requests
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGIN_REGEXES = [
    # Matches http:// or https:// for any exploretheworld.tech subdomain
    r"^https?://([a-zA-Z0-9_-]+\.)*exploretheworld\.tech(:\d+)?$",
]

# Dynamically add IP regexes if they exist in .env
for ip in [os.environ['TAILSCALE_HOST_IP'], os.environ['DOCKER_HOST_IP']]:
    if ip:
        escaped_ip = re.escape(ip)  # Turns "100.69.34.1" into "100\.69\.34\.1"
        CORS_ALLOWED_ORIGIN_REGEXES.append(fr"^https?://{escaped_ip}(:\d+)?$")

ACCOUNT_ALLOW_OAuth2_REDIRECTS = True
ALLOWED_REDIRECT_HOSTS = [os.environ['FRONTEND_DOMAIN'], os.environ['FRONTEND_DEV_DOMAIN']]

ACCOUNT_ADAPTER = 'picasa.adapters.SubdomainRedirectAdapter'

# Trust your frontend domain to submit POST/PATCH/DELETE requests
CSRF_TRUSTED_ORIGINS = [
    f'https://{os.environ['FRONTEND_DOMAIN']}',
    f'https://{os.environ['FRONTEND_DEV_DOMAIN']}',
    f"https://{os.environ['API_DOMAIN']}",
    f'https://{os.environ['SLIDESHOW_DOMAIN']}', # Add this line
    # Tailscale IP access
    f'http://{os.environ['TAILSCALE_HOST_IP']}',
    f'https://{os.environ['TAILSCALE_HOST_IP']}',
    # If your frontend runs on a specific port (e.g. 3000 or 8080), include it:
    # 'http://100.69.34.1:3000',

    # Local LAN IP access
    f"http://{os.environ['DOCKER_HOST_IP']}",
    f"https://{os.environ['DOCKER_HOST_IP']}",
]

# Ensure the CSRF cookie is accessible across your subdomains
CSRF_COOKIE_DOMAIN = '.exploretheworld.tech'

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-slideshow-key',
]


LOGGER.debug("CORS allowing from all...")

ROOT_URLCONF = 'picasa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(THIS_DIR, 'html')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'picasa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASS,
        'HOST': DB_HOST,
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Token authentication: https://simpleisbetterthancomplex.com/tutorial/2018/11/22/how-to-implement-token-authentication-using-django-rest-framework.html
# Ensure SessionAuthentication is your top priority authentication class
REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # <-- And here
        # PhotoVerify mobile app: Authelia OIDC ID token as a Bearer token.
        'api.authentication.AutheliaOIDCAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100, 
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'EXCEPTION_HANDLER': 'picasa.exceptions.api_redirect_to_login_handler',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'
LOGGER.debug(f"Time zone is {TIME_ZONE}")
NON_DETECTED_FACE_ENCODING = [-999] * 512

# Fallback for FaceExtractor.reencode_missing_faces(): used only when a face
# has no stored kps AND a fresh crop-based detection also finds nothing (the
# original face may be too small/blurry/occluded to redetect in isolation).
# Deliberately a valid, unit-norm, uniform-magnitude vector -- unlike
# NON_DETECTED_FACE_ENCODING above (an out-of-range sentinel for a
# conceptually different case: an existing face whose box wasn't matched to
# any detection during a full-image reprocessing pass) -- so it behaves as a
# neutral, low-information point in the embedding space rather than an
# obviously-invalid one, and won't crash cosine-similarity math done
# elsewhere against real embeddings.
REENCODE_DEFAULT_ENCODING = [512 ** -0.5] * 512

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CELERY STUFF
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:6379'
# CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379'
result_backend = f'redis://{REDIS_HOST}:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
accept_content = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
task_serializer = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
result_serializer = 'json'
# CELERY_TIMEZONE = TIME_ZONE
time_zone = TIME_ZONE
MAX_CELERY_TIME = 60 * 60 * 3 # 3 hours

CELERYD_USER = ""
CELERYD_GROUP = ""

# if production: 
CELERY_BEAT_SCHEDULE = {
    'filepopulate_root': {
        'task': 'filepopulator.populate_files_from_root',
        'schedule': crontab(hour='*', minute='*/10'),
        # 'schedule': crontab(minute='*'),
    },
    'dirs_datetimes': {
        'task': 'filepopulator.update_dir_dates',
        'schedule': crontab(minute=0, hour='*/12')
    },
   'face_add': {
       'task': 'face_manager.face_extraction', 
        # 'schedule': crontab( hour = '*', minute='5,15,25,35,45,55'),
       'schedule': crontab( hour = '*', minute='0'),
        # OK to schedule every 2 minutes, because it will
        # either get locked by the lock file, or it will
        # die and get restarted pretty quickly.
       # 'options': {
       #     'expires': 30,
       # }
   },
   'check_mods': {
        'task': 'filepopulator.check_mod_dates',
        'schedule': crontab(minute='0', hour = '23'),
    },
   'geocode_new_images': {
        'task': 'filepopulator.geocode_new_images',
        'schedule': crontab(minute='30', hour='*'),
    },
   'find_similar_images': {
        'task': 'filepopulator.find_similar_images',
        'schedule': crontab(minute='45', hour='*'),
    },
   'reencode_missing_faces': {
        'task': 'face_manager.reencode',
        'schedule': crontab(minute='20', hour='*'),
    },
   'clear_ignored_encodings': {
        'task': 'face_manager.clear_ignored_encodings',
        'schedule': crontab(minute='35', hour='*'),
    },
   'set_face_counts': {
       'task': 'face_manager.set_face_counts',
       'schedule': crontab( minute = '55', hour='*/4'),
   },
   'cluster_unverified_faces': {
        'task': 'face_manager.cluster_unverified_faces',
        # 1am -- clear of db_picasa's daily backup (2am) and weekly
        # vacuum-swap (3am Monday) jobs.
        'schedule': crontab(minute='0', hour='1'),
    },
  'classify_unlabeled': {
      'task': 'face_manager.assign_faces',
      'schedule': crontab( minute = '0', hour='*'),
      'args': (False, ), # Don't reassign all of them.
  },
   # 'classify_unlabeled_all_weekly': {
   #     'task': 'face_manager.assign_faces',
   #     # This schedule should be sufficient to
   #     # break race conditions with the more frequent
   #     # task, which executes every 5 minutes. That
   #     # should have very little to do on a run-to-run basis,
   #     # so it should finish quickly and be done by the 
   #     # time that minute 4 comes along and asks to 
   #     # reclassify all of the faces. 
   #     'schedule': crontab( minute = '4', hour='1', day_of_week=1),
   #     'args': (True, ), # Reassign all faces. 
   # },


}


if not 'filepopulate_root' in CELERY_BEAT_SCHEDULE.keys():
    LOGGER.error("Filepopulate celery task not instantiated.")
    raise ValueError('Filepopulate celery task not instantiated.')
if not 'dirs_datetimes' in CELERY_BEAT_SCHEDULE.keys():
    LOGGER.error("Dirs_datetimes celery task not instantiated.")
    raise ValueError('Dirs_datetimes celery task not instantiated.')

# FILEPOPULATOR settings


# FILEPOPULATOR_THUMBNAIL_DIR = '/home/benjamin/git_repos/picasa_files/thumbnails' # place to store thumbnails that are derived from the images. 
# FILEPOPULATOR_THUMBNAIL_SIZE_TINY = (30, 30)
# FILEPOPULATOR_THUMBNAIL_SIZE = (250, 250)
FILEPOPULATOR_THUMBNAIL_SIZE_BIG = (500, 500)
FILEPOPULATOR_THUMBNAIL_SIZE_MEDIUM = (250, 250)
FILEPOPULATOR_THUMBNAIL_SIZE_SMALL = (100, 100)
FILEPOPULATOR_SERVER_IMG_DIR = PHOTO_ROOT # root location of images you want to index into. (This maybe will change)
FILEPOPULATOR_CODE_DIR = PROJECT_ROOT # '/home/benjamin/git_repos/local_picasa' # root directory of the code. 
FILEPOPULATOR_VAL_DIRECTORY = TEST_IMG_DIR_FILEPOPULATE  # point to a directory that will have validation images when testing the app.
FILEPOPULATOR_MAX_SHORT_EDGE_THUMBNAIL = 150 # Maximum size of the short edge for thumbnails.
SLIDESHOW_API_KEY = os.environ['PICASA_API_KEY']

FACE_THUMBNAIL_SIZE=(200, 200)

# logging.error("TODO: Set up apache server. STATIC_URL needs to be served by it.")

BLANK_FACE_NAME='_NO_FACE_ASSIGNED_'
BLANK_FACE_IMG_PATH=os.path.join(SITE_ROOT, 'blank_person.png')

# Parameters for the machine learning model
if DEV:
    FACE_NUM_THRESH = 1
else:
    FACE_NUM_THRESH=50
# SOFT_IGNORE_NAME used to be its own sentinel Person ('.another_ignore'),
# separate from the '.ignore' a human assigns via the UI's close_unassigned
# action -- that meant the assign_faces classifier's low-confidence
# suggestions and the UI's own ignore state were never the same Person, so
# api/views.py's close_ignored bulk action could never recognize a
# classifier-suggested candidate. Collapsed into one identity so both paths
# agree; see merge_another_ignore_into_ignore management command for the
# one-time data migration that reassigns any existing '.another_ignore'
# Face references over to '.ignore'.
SOFT_IGNORE_NAME = '.ignore'
IGNORED_NAMES=[BLANK_FACE_NAME, SOFT_IGNORE_NAME, '.realignore', '.jessicatodo', '.cutler_tbd']
CLASSIFY_MODEL_PATH = '/code/face_manager/face_classifier/models'
DEFAULT_RESOLUTION_HEIGHT = 2160 # For 4k screens
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
APPEND_SLASH=True # Allow URLs to append a trailing slash


# print("STATIC is : ", STATIC_URL)
