# Generated by Django 5.2.6 on 2025-09-19 02:06

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import face_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filepopulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=256)),
                ('highlight_img', models.ImageField(default=None, upload_to=face_manager.models.face_highlight_path)),
                ('further_images_unlikely', models.BooleanField(default=False)),
                ('num_faces', models.IntegerField(default=0)),
                ('num_possibilities', models.IntegerField(default=0)),
                ('num_unverified_faces', models.IntegerField(default=0)),
                ('gender', models.CharField(default='unknown', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTakenUTC', models.FloatField(default=0)),
                ('reencoded', models.BooleanField(default=False)),
                ('face_encoding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=128)),
                ('face_encoding_512', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=512)),
                ('weight_1', models.FloatField(default=0.0)),
                ('weight_2', models.FloatField(default=0.0)),
                ('weight_3', models.FloatField(default=0.0)),
                ('weight_4', models.FloatField(default=0.0)),
                ('weight_5', models.FloatField(default=0.0)),
                ('written_to_photo_metadata', models.BooleanField(default=False)),
                ('rejected_fields', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=128)),
                ('box_top', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1)])),
                ('box_bottom', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1)])),
                ('box_left', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1)])),
                ('box_right', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1)])),
                ('face_thumbnail', models.ImageField(default=None, upload_to=face_manager.models.face_thumbnail_path)),
                ('validated', models.BooleanField(default=False)),
                ('detected_gender', models.CharField(default='unknown', max_length=15)),
                ('detected_gender_prob', models.FloatField(default=-1)),
                ('detected_age_group', models.IntegerField(default=-1)),
                ('detected_age_prob', models.FloatField(default=-1)),
                ('source_image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filepopulator.imagefile')),
                ('declared_name', models.ForeignKey(blank=True, null=True, on_delete=models.SET(face_manager.models.get_default_blank_person), related_name='face_declared', to='face_manager.person')),
                ('poss_ident1', models.ForeignKey(blank=True, null=True, on_delete=models.SET(face_manager.models.get_default_blank_person), related_name='face_poss1', to='face_manager.person')),
                ('poss_ident2', models.ForeignKey(blank=True, null=True, on_delete=models.SET(face_manager.models.get_default_blank_person), related_name='face_poss2', to='face_manager.person')),
                ('poss_ident3', models.ForeignKey(blank=True, null=True, on_delete=models.SET(face_manager.models.get_default_blank_person), related_name='face_poss3', to='face_manager.person')),
                ('poss_ident4', models.ForeignKey(blank=True, null=True, on_delete=models.SET(face_manager.models.get_default_blank_person), related_name='face_poss4', to='face_manager.person')),
                ('poss_ident5', models.ForeignKey(blank=True, null=True, on_delete=models.SET(face_manager.models.get_default_blank_person), related_name='face_poss5', to='face_manager.person')),
            ],
        ),
    ]
