# Generated by Django 5.2.7 on 2025-10-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='detected_age',
            field=models.IntegerField(default=-1),
        ),
    ]
