# Generated by Django 6.0.8 on 2026-08-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0003_seed_sentinel_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='face_encoding',
        ),
    ]
