# Generated by Django 6.0.8 on 2026-08-27 03:22

import django.contrib.postgres.fields
import face_manager.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0004_remove_face_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face_encoding_512',
            field=django.contrib.postgres.fields.ArrayField(base_field=face_manager.models.SingleFloatField(), blank=True, null=True, size=512),
        ),
    ]
