# Generated by Django 6.0.8 on 2026-08-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0005_alter_face_face_encoding_512'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='mobile_review_hidden',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
