# Generated by Django 6.0.8 on 2026-08-31 13:18

import django.contrib.postgres.fields
import face_manager.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0006_face_mobile_review_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='kps',
            field=django.contrib.postgres.fields.ArrayField(base_field=face_manager.models.SingleFloatField(), blank=True, null=True, size=10),
        ),
    ]
