# Generated by Django 6.0.8 on 2026-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0007_face_kps'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='verification_cluster_group',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
