# Generated by Django 6.0.8 on 2026-09-08 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0010_face_count_covering_indexes'),
        ('filepopulator', '0008_videofile_file_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='source_video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filepopulator.videofile'),
        ),
        migrations.AddField(
            model_name='face',
            name='video_first_timestamp_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='face',
            name='video_last_timestamp_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='face',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_image_file__isnull', False), ('source_video_file__isnull', True)), models.Q(('source_image_file__isnull', True), ('source_video_file__isnull', False)), _connector='OR'), name='face_exactly_one_source'),
        ),
    ]
