# Generated by Django 6.0.8 on 2026-09-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0011_face_source_video_file_and_more'),
        ('filepopulator', '0008_videofile_file_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='video_thumbnail_frame_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='face',
            constraint=models.CheckConstraint(condition=models.Q(('source_video_file__isnull', False), models.Q(('video_first_timestamp_seconds__isnull', True), ('video_last_timestamp_seconds__isnull', True), ('video_thumbnail_frame_seconds__isnull', True)), _connector='OR'), name='face_video_fields_require_video_source'),
        ),
    ]
