# Generated by Django 6.0.8 on 2026-09-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0011_face_source_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='video_thumbnail_frame_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
