# Generated by Django 6.0.8 on 2026-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_manager', '0012_face_video_thumbnail_frame_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='det_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
